# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introduction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('birthday', models.DateField()),
                ('university', models.CharField(max_length=200)),
                ('registered', models.DateTimeField(verbose_name='register date')),
            ],
        ),
    ]
