# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introduction', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(verbose_name='YYYY-MM-DD'),
        ),
    ]
