# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introduction', '0003_auto_20160313_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(verbose_name='Date of birth'),
        ),
    ]
